---
lightbox: true
---

# Using EBASE {#sec-ebase}

## Lesson Outline

This lesson will explain the basic theory behind ecosystem metabolism and how EBASE is used to estimate key parameters.  EBASE is a Bayesian implementation for estimating metabolism that differs from more conventional approaches.  We'll also explore the main functions of EBASE to estimate metabolism, how the Bayesian approach can be used to incorporate prior knowledge, and interpret the results. 

## Learning Goals

- Understand the basic theories of EBASE
- Understand the Bayesian approach to estimating metabolism
- Learn how EBASE is used to estimate key parameters
- Use the main functions of EBASE to estimate metabolism
- Interpret the results of EBASE

## The EBASE method

[Lesson @sec-intro] provided a general description of ecosystem metabolism and why it's an important measure of ecosystem health.  The EBASE approach follows these general principles but differs in the core model for estimating production, respiration, and gas exchange and the statistical approach for how the parameters for each are estimated.  Let's revisit the core metabolic equation: 

$$ 
NEM = P - R
$$

Net ecosystem metabolism ($NEM$) is simply the difference between processes that produce organic matter (production or $P$) and those that consume organic matter (respiration or $R$).  

We can estimate these rates from the dissolved oxygen ($DO$) time series by using the rate of change of $DO$ per unit time and accounting for gas exchange $D$.  Water column depth ($Z$) is used to estimate metabolism as an areal rate. 

$$
Z\frac{dC_d}{dt} = P - R + D
$$

Methods for estimating metabolism from the dissolved oxygen time series vary in how each of the key parameters are modeled.  The core equation for EBASE is the same as the previous but expanded using methods for estuarine applications: 

$$
Z\frac{dC_d}{dt} = aPAR - R + bU_{10}^2\left(\frac{Sc}{600} \right)^{-0.5} \left(C_{Sat} - C_d \right )
$$

$aPAR$ is production ($P$), $R$ is respiration, and the last term is gas exchange [$D$, @Wanninkohf14].  The required input data to fit this model was described in [Lesson @sec-dataprep].  Three of these inputs are used directly in the equation as $C_d$ for dissolved oxygen, $PAR$, and wind speed as $U_{10}^2$ (or squared wind speed at ten meters above the surface).  The other terms are the Schmidt number ($S_c$) and dissolved oxygen at saturation ($C_{sat}$), both of which are calculated from water temperature and salinity in the input data. 

The remaining terms $a$, $R$, and $b$ are estimated during the model fitting process, which we'll discuss in the next section.  All three provide important information about metabolic processes and are useful on their own to understand ecosystem function.

* $a$: The light efficiency parameter as $\left(mmol~O_2~m^{-2}~d^{-1}\right) / \left(W~m^{-2}\right)$, yields production when multiplied by $PAR$.  This is a measure of how efficiently light is converted to organic matter.  It provides similar information as a P/I curve by showing how production changes with light availability.
* $R$: The respiration rate as $mmol~O_2~m^{-2}~d^{-1}$, is the rate at which organic matter is consumed.
* $b$: The sensitivity of gas exchange to wind speed as $\left(cm~h^{-1}\right / \left(m^2~s^{-2}\right)$.

Although the core model equation may seem complicated, its formulation was chosen to describe dominant processes that influence metabolism in an estuarine setting.  The details for this justification can be found in @Beck2024.

## The Bayesian approach

The conventional open-water method presented by @Odum56 is similar to EBASE in that it uses the rate of change of $DO$ to estimate metabolism.  However, the Bayesian approach used in EBASE differs in how the parameters are estimated and has several key advantages.  

## EBASE prep

* Missing data

## Next steps

You now understand the basics of ecosystem metabolism and how EBASE is used to estimate key parameters using a Bayesian approach.  We've explored additional functions in EBASE to help interpret the results, which include an evaluation of goodness of fit and various plotting methods.  Next, we'll explore the EBASE results in more detail to demonstrate how the results can inform the understanding of ecosystem health and function.