---
lightbox: true
---

# Interpreting Results

## Lesson Outline

The EBASE package includes a few functions to quickly assess the results of the metabolism analysis.  Additional tools are available in R to develop a more detailed understanding of factors that might influence the metabolic rates.  This lesson will provide some quick demonstrations of how to use R for more in depth analyses that will help you understand differences within and between coastal areas. 

## Learning Goals

- Understand how to manipulate or wrangle EBASE results for further analysis
- Combine EBASE results with additional data
- Perform simple analyses to evaluate hypotheses about factors influencing metabolism

## Next steps

This concludes our workshop on using EBASE to estimate ecosystem metabolism.  You should now have a baseline understanding of how these tools can be used to gain insights into ecosystem properties and the factors that may be influencing them. Please follow up with the instructor if you have additional questions or would like to explore more advanced topics.